/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { DecimalBalanceAmount } from './decimal-balance-amount.model';

export interface IBalancesInDecimalDto {
    nativeBalance?: DecimalBalanceAmount;
    nativeFreeDecimalBalanceString?: string;
    nativeLockedDecimalBalanceString?: string;
    nonNativeBalances?: object;
    nonNativeBalancesString?: object;
}


export class BalancesInDecimalDto extends BaseModel implements IBalancesInDecimalDto  {
    nativeBalance: DecimalBalanceAmount;
    nativeFreeDecimalBalanceString: string;
    nativeLockedDecimalBalanceString: string;
    nonNativeBalances: object;
    nonNativeBalancesString: object;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();
        this.nativeBalance = new DecimalBalanceAmount(); 

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.nativeBalance.setValues(rawValues.nativeBalance, useFormGroupValuesToModel);
            this.nativeFreeDecimalBalanceString = rawValues.nativeFreeDecimalBalanceString;
            this.nativeLockedDecimalBalanceString = rawValues.nativeLockedDecimalBalanceString;
            this.nonNativeBalances = rawValues.nonNativeBalances;
            this.nonNativeBalancesString = rawValues.nonNativeBalancesString;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                nativeBalance: this.nativeBalance.$formGroup,
                nativeFreeDecimalBalanceString: new FormControl(this.nativeFreeDecimalBalanceString),
                nativeLockedDecimalBalanceString: new FormControl(this.nativeLockedDecimalBalanceString),
                nonNativeBalances: new FormControl(this.nonNativeBalances),
                nonNativeBalancesString: new FormControl(this.nonNativeBalancesString),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.nativeBalance.setFormGroupValues();
        this.$formGroup.controls['nativeFreeDecimalBalanceString'].setValue(this.nativeFreeDecimalBalanceString);
        this.$formGroup.controls['nativeLockedDecimalBalanceString'].setValue(this.nativeLockedDecimalBalanceString);
        this.$formGroup.controls['nonNativeBalances'].setValue(this.nonNativeBalances);
        this.$formGroup.controls['nonNativeBalancesString'].setValue(this.nonNativeBalancesString);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

