/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { CreateTrustLineInternalDto } from './create-trust-line-internal-dto.model';

export interface IBulkCreateTrustLineDto {
    trustLineData?: Array<CreateTrustLineInternalDto>;
}


export class BulkCreateTrustLineDto extends BaseModel implements IBulkCreateTrustLineDto  {
    trustLineData: Array<CreateTrustLineInternalDto>;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();
        this.trustLineData = new Array<CreateTrustLineInternalDto>(); 

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.fillModelArray<CreateTrustLineInternalDto>(this, 'trustLineData', rawValues.trustLineData, useFormGroupValuesToModel, CreateTrustLineInternalDto, SubTypeFactory.createSubTypeInstance);
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                trustLineData: new FormArray([]),
            });
            // generate FormArray control elements
            this.fillFormArray<CreateTrustLineInternalDto>('trustLineData', this.trustLineData, CreateTrustLineInternalDto);
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.fillFormArray<CreateTrustLineInternalDto>('trustLineData', this.trustLineData, CreateTrustLineInternalDto);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

