/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { MetadataOrganizationDocumentation } from './metadata-organization-documentation.model';
import { MetadataPrincipal } from './metadata-principal.model';
import { MetadataCurrency } from './metadata-currency.model';
import { SimpleAccessCredentialsDto } from './simple-access-credentials-dto.model';

export interface ICreateMetadataFileDto {
    documentation?: MetadataOrganizationDocumentation;
    principals?: Array<MetadataPrincipal>;
    currency?: MetadataCurrency;
    subDomain?: string;
    credentials?: SimpleAccessCredentialsDto;
}


export class CreateMetadataFileDto extends BaseModel implements ICreateMetadataFileDto  {
    documentation: MetadataOrganizationDocumentation;
    principals: Array<MetadataPrincipal>;
    currency: MetadataCurrency;
    subDomain: string;
    credentials: SimpleAccessCredentialsDto;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();
        this.documentation = new MetadataOrganizationDocumentation(); 
        this.principals = new Array<MetadataPrincipal>(); 
        this.currency = new MetadataCurrency(); 
        this.credentials = new SimpleAccessCredentialsDto(); 

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.documentation.setValues(rawValues.documentation, useFormGroupValuesToModel);
            this.fillModelArray<MetadataPrincipal>(this, 'principals', rawValues.principals, useFormGroupValuesToModel, MetadataPrincipal, SubTypeFactory.createSubTypeInstance);
            this.currency.setValues(rawValues.currency, useFormGroupValuesToModel);
            this.subDomain = rawValues.subDomain;
            this.credentials.setValues(rawValues.credentials, useFormGroupValuesToModel);
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                documentation: this.documentation.$formGroup,
                principals: new FormArray([]),
                currency: this.currency.$formGroup,
                subDomain: new FormControl(this.subDomain),
                credentials: this.credentials.$formGroup,
            });
            // generate FormArray control elements
            this.fillFormArray<MetadataPrincipal>('principals', this.principals, MetadataPrincipal);
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.documentation.setFormGroupValues();
        this.fillFormArray<MetadataPrincipal>('principals', this.principals, MetadataPrincipal);
        this.currency.setFormGroupValues();
        this.$formGroup.controls['subDomain'].setValue(this.subDomain);
        this.credentials.setFormGroupValues();
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

