/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface IDepotPaymentSummaryBankAccountDto {
    holder?: string;
    iban?: string;
    bic?: string;
}


export class DepotPaymentSummaryBankAccountDto extends BaseModel implements IDepotPaymentSummaryBankAccountDto  {
    holder: string;
    iban: string;
    bic: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.holder = rawValues.holder;
            this.iban = rawValues.iban;
            this.bic = rawValues.bic;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                holder: new FormControl(this.holder),
                iban: new FormControl(this.iban),
                bic: new FormControl(this.bic),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['holder'].setValue(this.holder);
        this.$formGroup.controls['iban'].setValue(this.iban);
        this.$formGroup.controls['bic'].setValue(this.bic);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

