/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface IEtfValueDto {
    date?: Date;
    depotValue?: number;
    cashValue?: number;
}


export class EtfValueDto extends BaseModel implements IEtfValueDto  {
    date: Date;
    depotValue: number;
    cashValue: number;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.date = rawValues.date;
            this.depotValue = rawValues.depotValue;
            this.cashValue = rawValues.cashValue;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                date: new FormControl(this.date),
                depotValue: new FormControl(this.depotValue),
                cashValue: new FormControl(this.cashValue),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['date'].setValue(this.date);
        this.$formGroup.controls['depotValue'].setValue(this.depotValue);
        this.$formGroup.controls['cashValue'].setValue(this.cashValue);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

