/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { CreateExternalRetailWalletDto } from './create-external-retail-wallet-dto.model';

export interface IImportExternalRetailWalletDto {
    wallets?: Array<CreateExternalRetailWalletDto>;
}


export class ImportExternalRetailWalletDto extends BaseModel implements IImportExternalRetailWalletDto  {
    wallets: Array<CreateExternalRetailWalletDto>;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();
        this.wallets = new Array<CreateExternalRetailWalletDto>(); 

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.fillModelArray<CreateExternalRetailWalletDto>(this, 'wallets', rawValues.wallets, useFormGroupValuesToModel, CreateExternalRetailWalletDto, SubTypeFactory.createSubTypeInstance);
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                wallets: new FormArray([]),
            });
            // generate FormArray control elements
            this.fillFormArray<CreateExternalRetailWalletDto>('wallets', this.wallets, CreateExternalRetailWalletDto);
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.fillFormArray<CreateExternalRetailWalletDto>('wallets', this.wallets, CreateExternalRetailWalletDto);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

