/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface IInitTokenizedAssetCreationDto {
    name?: string;
    unitName?: string;
    totalSupply?: number;
    decimals?: number;
    enableFreeze?: boolean;
    enableClawback?: boolean;
    url?: string;
    metaData?: string;
    distributorWalletId?: string;
}


export class InitTokenizedAssetCreationDto extends BaseModel implements IInitTokenizedAssetCreationDto  {
    name: string;
    unitName: string;
    totalSupply: number;
    decimals: number;
    enableFreeze: boolean;
    enableClawback: boolean;
    url: string;
    metaData: string;
    distributorWalletId: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.name = rawValues.name;
            this.unitName = rawValues.unitName;
            this.totalSupply = rawValues.totalSupply;
            this.decimals = rawValues.decimals;
            this.enableFreeze = rawValues.enableFreeze;
            this.enableClawback = rawValues.enableClawback;
            this.url = rawValues.url;
            this.metaData = rawValues.metaData;
            this.distributorWalletId = rawValues.distributorWalletId;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                name: new FormControl(this.name),
                unitName: new FormControl(this.unitName),
                totalSupply: new FormControl(this.totalSupply),
                decimals: new FormControl(this.decimals),
                enableFreeze: new FormControl(this.enableFreeze),
                enableClawback: new FormControl(this.enableClawback),
                url: new FormControl(this.url),
                metaData: new FormControl(this.metaData),
                distributorWalletId: new FormControl(this.distributorWalletId),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['name'].setValue(this.name);
        this.$formGroup.controls['unitName'].setValue(this.unitName);
        this.$formGroup.controls['totalSupply'].setValue(this.totalSupply);
        this.$formGroup.controls['decimals'].setValue(this.decimals);
        this.$formGroup.controls['enableFreeze'].setValue(this.enableFreeze);
        this.$formGroup.controls['enableClawback'].setValue(this.enableClawback);
        this.$formGroup.controls['url'].setValue(this.url);
        this.$formGroup.controls['metaData'].setValue(this.metaData);
        this.$formGroup.controls['distributorWalletId'].setValue(this.distributorWalletId);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

