/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface ISimpleAccessCredentialsDto {
    passphrase: string;
    keyFileContent?: string;
}


export class SimpleAccessCredentialsDto extends BaseModel implements ISimpleAccessCredentialsDto  {
    passphrase: string;
    keyFileContent: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.passphrase = rawValues.passphrase;
            this.keyFileContent = rawValues.keyFileContent;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                passphrase: new FormControl(this.passphrase, [Validators.required, ]),
                keyFileContent: new FormControl(this.keyFileContent),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['passphrase'].setValue(this.passphrase);
        this.$formGroup.controls['keyFileContent'].setValue(this.keyFileContent);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

