/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface ITokenizedAssetClawbackTransfer {
    retailWalletId?: string;
    amount?: number;
}


export class TokenizedAssetClawbackTransfer extends BaseModel implements ITokenizedAssetClawbackTransfer  {
    retailWalletId: string;
    amount: number;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.retailWalletId = rawValues.retailWalletId;
            this.amount = rawValues.amount;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                retailWalletId: new FormControl(this.retailWalletId),
                amount: new FormControl(this.amount),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['retailWalletId'].setValue(this.retailWalletId);
        this.$formGroup.controls['amount'].setValue(this.amount);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

