/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface ITokenizedAssetOptInDto {
    id?: string;
    txId?: string;
    fee?: string;
    confirmed?: Date;
}


export class TokenizedAssetOptInDto extends BaseModel implements ITokenizedAssetOptInDto  {
    id: string;
    txId: string;
    fee: string;
    confirmed: Date;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.id = rawValues.id;
            this.txId = rawValues.txId;
            this.fee = rawValues.fee;
            this.confirmed = rawValues.confirmed;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                id: new FormControl(this.id),
                txId: new FormControl(this.txId),
                fee: new FormControl(this.fee),
                confirmed: new FormControl(this.confirmed),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['id'].setValue(this.id);
        this.$formGroup.controls['txId'].setValue(this.txId);
        this.$formGroup.controls['fee'].setValue(this.fee);
        this.$formGroup.controls['confirmed'].setValue(this.confirmed);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

