/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { OptInStatus } from './enums';

export interface ITokenizedAssetOptInDto {
    id?: string;
    txId?: string;
    confirmed?: Date;
    customerId?: string;
    retailWalletId?: string;
    created?: Date;
    status?: OptInStatus;
}


export class TokenizedAssetOptInDto extends BaseModel implements ITokenizedAssetOptInDto  {
    id: string;
    txId: string;
    confirmed: Date;
    customerId: string;
    retailWalletId: string;
    created: Date;
    status: OptInStatus;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.id = rawValues.id;
            this.txId = rawValues.txId;
            this.confirmed = rawValues.confirmed;
            this.customerId = rawValues.customerId;
            this.retailWalletId = rawValues.retailWalletId;
            this.created = rawValues.created;
            this.status = rawValues.status;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                id: new FormControl(this.id),
                txId: new FormControl(this.txId),
                confirmed: new FormControl(this.confirmed),
                customerId: new FormControl(this.customerId),
                retailWalletId: new FormControl(this.retailWalletId),
                created: new FormControl(this.created),
                status: new FormControl(this.status, [enumValidator(OptInStatus), ]),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['id'].setValue(this.id);
        this.$formGroup.controls['txId'].setValue(this.txId);
        this.$formGroup.controls['confirmed'].setValue(this.confirmed);
        this.$formGroup.controls['customerId'].setValue(this.customerId);
        this.$formGroup.controls['retailWalletId'].setValue(this.retailWalletId);
        this.$formGroup.controls['created'].setValue(this.created);
        this.$formGroup.controls['status'].setValue(this.status);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

