/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


import { WalletType } from './enums';

export interface IWalletBasicInfoDto {
    type?: WalletType;
    publicKey?: string;
    id?: string;
}


export class WalletBasicInfoDto extends BaseModel implements IWalletBasicInfoDto  {
    type: WalletType;
    publicKey: string;
    id: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.type = rawValues.type;
            this.publicKey = rawValues.publicKey;
            this.id = rawValues.id;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                type: new FormControl(this.type, [enumValidator(WalletType), ]),
                publicKey: new FormControl(this.publicKey),
                id: new FormControl(this.id),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['type'].setValue(this.type);
        this.$formGroup.controls['publicKey'].setValue(this.publicKey);
        this.$formGroup.controls['id'].setValue(this.id);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

