/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';



export interface IWealthManagementDocumentDto {
    id?: string;
    name?: string;
    created?: Date;
    categoryId?: number;
    categoryName?: string;
    new?: boolean;
    url?: string;
}


export class WealthManagementDocumentDto extends BaseModel implements IWealthManagementDocumentDto  {
    id: string;
    name: string;
    created: Date;
    categoryId: number;
    categoryName: string;
    new: boolean;
    url: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
     * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: any, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.id = rawValues.id;
            this.name = rawValues.name;
            this.created = rawValues.created;
            this.categoryId = rawValues.categoryId;
            this.categoryName = rawValues.categoryName;
            this.new = rawValues.new;
            this.url = rawValues.url;
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                id: new FormControl(this.id),
                name: new FormControl(this.name),
                created: new FormControl(this.created),
                categoryId: new FormControl(this.categoryId),
                categoryName: new FormControl(this.categoryName),
                new: new FormControl(this.new),
                url: new FormControl(this.url),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls['id'].setValue(this.id);
        this.$formGroup.controls['name'].setValue(this.name);
        this.$formGroup.controls['created'].setValue(this.created);
        this.$formGroup.controls['categoryId'].setValue(this.categoryId);
        this.$formGroup.controls['categoryName'].setValue(this.categoryName);
        this.$formGroup.controls['new'].setValue(this.new);
        this.$formGroup.controls['url'].setValue(this.url);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}

